name: "airbyte_pipedrive"
version: "0.1.0"
require-dbt-version: [">=1.0.0"]
config-version: 2
profile: "default"
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_pipedrive:
    materialized: table
    tmp:
      materialized: view

vars:
  airbyte_pipedrive:
    activities: "{{ source('airbyte_pipedrive','activities') }}"
    deals: "{{ source('airbyte_pipedrive','deals') }}"
    leads: "{{ source('airbyte_pipedrive','leads') }}"
    leads_value: "{{ source('airbyte_pipedrive','leads_value') }}"
    stages: "{{ source('airbyte_pipedrive','stages') }}"
    users: "{{ source('airbyte_pipedrive','users') }}"
