version: 2

sources:
  - name: airbyte_pipedrive
    schema: "{{ var('pipedrive_schema', 'pipedrive') }}"
    database: "{% if target.type != 'spark'%}{{ var('pipedrive_database', target.database) }}{% endif %}"
    tables:
      - name: activities
      - name: deals
      - name: leads
      - name: leads_value
      - name: stages
      - name: users

models:
  - name: pipedrive__deals
    description: "A table storing all deal information in Pipedrive."
    columns:
      - name: deal_id
        description: "The unique identifier for the deal"
        tests:
          - unique
          - not_null

metrics:
  - name: number_of_deals
    label: Number of deals
    model: ref('pipedrive__deals')
    description: "The number of deals"

    type: count
    sql: issue_id

    timestamp: created_at_timestamp
    time_grains: [ day, week, month ]

    dimensions:
      - state

