version: 2

sources:
  - name: airbyte_pipedrive
    schema: "{{ var('pipedrive_schema', 'pipedrive') }}"
    database: "{% if target.type != 'spark'%}{{ var('pipedrive_database', target.database) }}{% endif %}"
    tables:
      - name: activities
      - name: deals
      - name: leads
      - name: leads_value
      - name: stages
      - name: users

models:
  - name: pipedrive__activities
    database: "{% if target.type != 'spark'%}{{ var('pipedrive_database', target.database) }}{% endif %}"
    table: activities
    columns:
      - name: activity_id
        description: "The unique identifier for the activity"
        tests:
          - not_null
          - unique
      - name: updated_at_date
        description: "The date the activity was last updated"
      - name: user_id
        description: "The user id that performed this activity"
        tests:
          - not_null
      - name: user_name
        description: "The user name that performed this activity"
      - name: type
        description: "The type of activity"
        tests:
          - not_null
      - name: is_done
        description: "Was the activity completed"
        tests:
          - not_null

  - name: pipedrive__deals
    description: "A table storing all deal information in Pipedrive."
    columns:
      - name: deal_id
        description: "The unique identifier for the deal"
        tests:
          - unique
          - not_null
      - name: created_at_date
        description: "The date the deal was created"
        tests:
          - not_null
      - name: closed_at_date
        description: "The date the deal was closed"
      - name: currency
        description: "The currency of the deal"
        tests:
          - not_null
      - name: deal_name
        description: "The name of the deal"
      - name: is_active
        description: "Is the deal active"
        tests:
          - not_null
      - name: is_deleted
        description: "Is the deal deleted"
        tests:
          - not_null
      - name: updated_at_date
        description: "The date the deal was last updated"
        tests:
          - not_null
      - name: weighted_value
        description: "The weighted value of the deal"
      - name: stage_name
        description: "The stage of the deal"
      - name: stage_id
        description: "The stage id of the deal"
      - name: user_id
        description: "The user id assigned to the deal"
      - name: user_name
        description: "The user name assigned to the deal"

  - name: pipedrive__leads
    description: "A table storing all lead information in Pipedrive."
    columns:
      - name: lead_id
        description: "The unique identifier for the lead"
        tests:
          - unique
          - not_null

  - name: pipedrive__users
    description: "A table storing all user information in Pipedrive."
    columns:
      - name: user_id
        description: "The unique identifier for the user"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "The name of the user"
        tests:
          - not_null
      - name: created_at_date
        description: "The date the user was created"
        tests:
          - not_null
      - name: is_active
        description: "Is the user active"
        tests:
          - not_null
      - name: is_admin
        description: "Is the user an admin"
        tests:
          - not_null

metrics:
  - name: number_of_deals
    label: Number of deals
    model: ref('pipedrive__deals')
    description: "The number of deals"

    type: count
    sql: issue_id

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - stage_id
      - user_id

  - name: number_of_activities
    label: Number of activities
    model: ref('pipedrive__activities')
    description: "The number of activities"

    type: count
    sql: activity_id

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - type
      - is_done
      - user_id

  - name: number_of_leads
    label: Number of leads
    model: ref('pipedrive__leads')
    description: "The number of leads"

    type: count
    sql: lead_id

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - user_id
      - source

  - name: total_lead_value
    label: Total Lead Value
    model: ref('pipedrive__leads')
    description: "The total value of all leads"

    type: sum
    sql: amount

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - user_id
      - source

  - name: average_lead_value
    label: Average Lead Value
    model: ref('pipedrive__leads')
    description: "The average value of all leads"

    type: average
    sql: amount

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - user_id
      - source

  - name: average_expected_time_to_close
    label: Average Expected Time To Close
    model: ref('pipedrive__leads')
    description: "The average expected time to close"

    type: average
    sql: expected_time_to_close

    timestamp: date
    time_grains: [ day, week, month ]

    dimensions:
      - user_id
      - source

  - name: number_of_users
    label: Number of users
    model: ref('pipedrive__users')
    description: "The number of users"

    type: count
    sql: user_id

    timestamp: created_at_date
    time_grains: [ day, week, month ]
