version: 2

sources:
  - name: airbyte_pipedrive
    schema: "{{ var('pipedrive_schema', 'pipedrive') }}"
    database: "{% if target.type != 'spark'%}{{ var('pipedrive_database', target.database) }}{% endif %}"
    tables:
      - name: users

models:
  - name: pipedrive__users
    description: "A table storing all user information in Pipedrive."
    columns:
      - name: user_id
        description: "The unique identifier for the user"
        tests:
          - unique
          - not_null

metrics:
  - name: number_of_users
    label: Number of users
    model: ref('pipedrive__users')
    description: "The number of users"

    type: count
    sql: issue_id

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

    dimensions:
      - state

